grants:
  view: 1
  edit: 1
  delete: 1
priority: 1
preserve: 1
_core:
  default_config_hash: Zno4MMkbreZeJZgnY0DXCPksXkuYye3MyIFlVuh-xLc
article:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
keynotes:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_album:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_canvas_page:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_event:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_presentation:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_product:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_program_entry:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_service:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_speaker:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_sponsor:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_team_member:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
mt_testimonial:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
page:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
zoom_meeting:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
zoom_registrant:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  eva_user:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
role_alias:
  anonymous:
    alias: 'Anonymous user'
    weight: '0'
    name: 'Anonymous user'
    allow: 0
  authenticated:
    alias: 'Authenticated user'
    weight: '0'
    name: 'Authenticated user'
    allow: 0
  administrator:
    alias: Administrator
    weight: '0'
    name: Administrator
    allow: 0
  eva_user:
    alias: 'EVA user'
    weight: '0'
    name: 'EVA user'
    allow: 0
  speaker:
    alias: Speaker
    name: Speaker
    weight: 0
    allow: 0
  attendees:
    alias: Attendees
    name: Attendees
    weight: 0
    allow: 0
  exhibitor:
    alias: Exhibitor
    name: Exhibitor
    weight: 0
    allow: 0
  cache_clear:
    alias: 'Limited Access'
    name: 'Limited Access'
    weight: 0
    allow: 0
  sponsor:
    alias: Sponsor
    name: Sponsor
    weight: 0
    allow: 0
role_map:
  anonymous: 1
  authenticated: 2
  administrator: 3
  eva_user: 4
  speaker: 5
  attendees: 6
  exhibitor: 7
  cache_clear: 8
  sponsor: 9
allowed_types:
  article: 1
  keynotes: 1
  mt_album: 1
  mt_canvas_page: 1
  mt_event: 1
  mt_presentation: 1
  mt_product: 1
  mt_program_entry: 1
  mt_service: 1
  mt_speaker: 1
  mt_sponsor: 1
  mt_team_member: 1
  mt_testimonial: 1
  page: 1
  zoom_meeting: 1
  zoom_registrant: 1
  forum: 0
  faq: 0
  tradeshow: 0
  poster: 0
forum:
  anonymous:
    grant_view: 1
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: 1
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
faq:
  anonymous:
    grant_view: 1
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: 1
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
tradeshow:
  anonymous:
    grant_view: 1
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: 1
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
poster:
  anonymous:
    grant_view: 1
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: 1
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
