# Schema for the configuration files of the Juicer module.

juicerio.settings:
  type: config_object
  label: 'Juicer settings'
  mapping:
    juicer_feed_id:
      type: text
      label: 'Juicer Username'
    juicer_blocks:
      type: text
      label: 'Number of Juicer feed blocks'