flag.flag.*.third_party.flag_anon:
  type: mapping
  label: 'Flag anonymous'
  mapping:
    enabled:
      type: integer
      label: 'Is enabled'
    label_display:
      type: string
      label: 'Label display mode'
    popin_title:
      type: label
      label: 'Dialog message title'
    message:
      type: label
      label: 'Message text'
    login_label:
      type: label
      label: 'Login link label'
    register_label:
      type: label
      label: 'Register link label'
    popup:
      type: integer
      label: 'Display Login/Register forms in popup'
    popup_login:
      type: string
      label: 'Popup Login link settings JSON'
    popup_register:
      type: string
      label: 'Popup Register link settings JSON'
